services:
  db:
    image: pgvector/pgvector:0.8.1-pg14-trixie
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hn_search
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
